#!/bin/sh
exec 1>&2
REPO_ROOT=$(git rev-parse --show-toplevel)

"$REPO_ROOT"/tools/lint.sh

exit_code=$?

if [ $exit_code -ne 0 ]; then
  echo "Linting failed. Please fix the errors and try again."
fi

exit $exit_code