name: Build and run unit tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Run Unit Tests
    runs-on: macos-15
    permissions:
      checks: write
      contents: read
    env:
      SCHEME: MakeMeStand
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: xcodebuild build-for-testing -scheme "$SCHEME" -skipPackagePluginValidation -skipMacroValidation
      - name: Test
        run: xcodebuild test-without-building -scheme "$SCHEME" -resultBundlePath TestLogs.xcresult
      # - name: Upload xcresult file
      #   uses: actions/upload-artifact@v4
      #   if: ${{ failure() }}
      #   with:
      #     name: TestsLogs-${{ github.run_number }}.xcresult
      #     path: TestsLogs.xcresult
      - uses: slidoapp/xcresulttool@v3.1.0
        with:
          path: TestLogs.xcresult
        if: success() || failure()
        
